CREATE DATABASE flight_db;
GRANT ALL PRIVILEGES ON DATABASE flight_db TO program;

CREATE DATABASE ticket_db;
GRANT ALL PRIVILEGES ON DATABASE ticket_db TO program;

CREATE DATABASE bonus_db;
GRANT ALL PRIVILEGES ON DATABASE bonus_db TO program;